title: sudo
description: "Some Nerdy Detritus"
url: "http://jbielich.github.io"
#url: "http://localhost:4000"
twitter_username: jbielich
github_username:  jbielich
language: en_US
paginate: 10
paginate_path: "/page/:num/"
permalink: none
markdown: kramdown
